### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mariogolf64** [kreiff/Cosmic_Loop#1]
Hi I am trying to build this project but have had a few problems getting it working and was wondering if you could answer some questions about it? 

My email is tomwilliamfield@hotmail.co.uk

Thanks!

**Comment by kreiff** [comment]
Hey Tom - Sent you an email. Sorry for the delay, didn't realized anyone had logged an issue as this is kind of an old project.

Feel free to reply with more details here or reply to my email.

**Comment by kreiff** [comment]
Going to close this issue now - because there aren't really specific action items to work from. Feel free to open another issue with more specific items.
